"""Add preferred_language to users

Revision ID: 20260605_0002
Revises: 20260605_0001
Create Date: 2026-06-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '20260605_0002'
down_revision = '20260605_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    # Check if column already exists to avoid errors
    conn = op.get_bind()
    
    # Query to check if column exists
    result = conn.execute(text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'users' 
        AND column_name = 'preferred_language'
    """))
    
    column_exists = result.fetchone() is not None
    
    if not column_exists:
        op.add_column('users', sa.Column('preferred_language', sa.String(length=5), nullable=False, server_default='cs'))
    else:
        # Column exists, ensure it has the correct default and constraints
        conn.execute(text("UPDATE users SET preferred_language = 'cs' WHERE preferred_language IS NULL"))
        conn.execute(text("ALTER TABLE users ALTER COLUMN preferred_language SET DEFAULT 'cs'"))
        # Make column NOT NULL by setting a default value for any NULL rows first
        conn.execute(text("ALTER TABLE users ALTER COLUMN preferred_language SET NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
