"""Add recommendation_text to report_section_summaries

Revision ID: 20260605_0001
Revises: 20260604_0001
Create Date: 2026-06-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260605_0001'
down_revision = '20260604_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('report_section_summaries', sa.Column('recommendation_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('report_section_summaries', 'recommendation_text')
    # ### end Alembic commands ###
