"""Add preferred_language to users

Revision ID: 20260605_0002
Revises: 20260605_0001
Create Date: 2026-06-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260605_0002'
down_revision = '20260605_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('users', sa.Column('preferred_language', sa.String(length=5), nullable=False, server_default='cs'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
