"""Make summary_text nullable in report_section_summaries

Revision ID: 20260616_0001
Revises: 20260609_0001
Create Date: 2026-06-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260616_0001'
down_revision: Union[str, None] = '20260609_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.alter_column('report_section_summaries', 'summary_text', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.alter_column('report_section_summaries', 'summary_text', nullable=False)
    # ### end Alembic commands ###
