"""Add encryption_status field to media model

Revision ID: 27fb702f917a
Revises: 57c58cebc89e
Create Date: 2026-04-22 17:57:21.354210
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fb702f917a'
down_revision = '57c58cebc89e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('encryption_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'encryption_status')
    # ### end Alembic commands ###
