"""Add audit_type and split legal requirement fields

Revision ID: 2b1fbe30fdaf
Revises: 907b3a2cc891
Create Date: 2026-04-22 19:22:56.945005
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1fbe30fdaf'
down_revision = '907b3a2cc891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('checklist_question_translations', sa.Column('legal_requirement_title', sa.String(length=500), nullable=True))
    op.add_column('checklist_question_translations', sa.Column('legal_requirement_description', sa.Text(), nullable=True))
    op.add_column('checklist_questions', sa.Column('audit_type', sa.String(length=50), nullable=True))
    
    # Update existing data
    op.execute("UPDATE checklist_question_translations SET legal_requirement_title = COALESCE(paragraph_title, 'Untitled') WHERE legal_requirement_title IS NULL")
    op.execute("UPDATE checklist_question_translations SET legal_requirement_description = question_text WHERE legal_requirement_description IS NULL")
    op.execute("UPDATE checklist_questions SET audit_type = 'compliance' WHERE audit_type IS NULL")
    
    # Now make columns non-nullable
    op.alter_column('checklist_question_translations', 'legal_requirement_title', nullable=False)
    op.alter_column('checklist_question_translations', 'legal_requirement_description', nullable=False)
    op.alter_column('checklist_questions', 'audit_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_questions', 'audit_type')
    op.drop_column('checklist_question_translations', 'legal_requirement_description')
    op.drop_column('checklist_question_translations', 'legal_requirement_title')
    # ### end Alembic commands ###
