"""Update question code uniqueness to section-level

Revision ID: 360657baa2c7
Revises: ce71bfc7845f
Create Date: 2026-04-30 23:42:46.321800
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '360657baa2c7'
down_revision = 'ce71bfc7845f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_admin_notes_report_id'), table_name='report_admin_notes')
    op.drop_table('report_admin_notes')
    op.drop_index(op.f('ix_report_admin_suggestions_report_id'), table_name='report_admin_suggestions')
    op.drop_table('report_admin_suggestions')
    op.drop_index(op.f('ix_answer_reviews_answer_id'), table_name='answer_reviews')
    op.drop_index(op.f('ix_answer_reviews_assessment_review_id'), table_name='answer_reviews')
    op.drop_index(op.f('ix_answer_reviews_is_action_required'), table_name='answer_reviews')
    op.drop_index(op.f('ix_answer_reviews_priority_level'), table_name='answer_reviews')
    op.drop_index(op.f('ix_answer_reviews_reviewer_id'), table_name='answer_reviews')
    op.alter_column('assessment_reviews', 'completion_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assessment_reviews_assessment_id'), table_name='assessment_reviews')
    op.drop_index(op.f('ix_assessment_reviews_reviewer_id'), table_name='assessment_reviews')
    op.drop_index(op.f('ix_assessment_reviews_status'), table_name='assessment_reviews')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_user_id'), table_name='audit_logs')
    op.drop_constraint(op.f('uq_questions_checklist_code'), 'checklist_questions', type_='unique')
    op.create_unique_constraint('uq_questions_checklist_code', 'checklist_questions', ['section_id', 'question_code'])
    op.drop_index(op.f('ix_review_history_assessment_review_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_created_at'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_reviewer_id'), table_name='review_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_review_history_reviewer_id'), 'review_history', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_history_created_at'), 'review_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_history_assessment_review_id'), 'review_history', ['assessment_review_id'], unique=False)
    op.drop_constraint('uq_questions_checklist_code', 'checklist_questions', type_='unique')
    op.create_unique_constraint(op.f('uq_questions_checklist_code'), 'checklist_questions', ['checklist_id', 'question_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_audit_logs_target_user_id'), 'audit_logs', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessment_reviews_status'), 'assessment_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_reviews_reviewer_id'), 'assessment_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_assessment_reviews_assessment_id'), 'assessment_reviews', ['assessment_id'], unique=False)
    op.alter_column('assessment_reviews', 'completion_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_answer_reviews_reviewer_id'), 'answer_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_answer_reviews_priority_level'), 'answer_reviews', ['priority_level'], unique=False)
    op.create_index(op.f('ix_answer_reviews_is_action_required'), 'answer_reviews', ['is_action_required'], unique=False)
    op.create_index(op.f('ix_answer_reviews_assessment_review_id'), 'answer_reviews', ['assessment_review_id'], unique=False)
    op.create_index(op.f('ix_answer_reviews_answer_id'), 'answer_reviews', ['answer_id'], unique=False)
    op.create_table('report_admin_suggestions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('suggestion_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('report_admin_suggestions_admin_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_admin_suggestions_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('report_admin_suggestions_pkey'))
    )
    op.create_index(op.f('ix_report_admin_suggestions_report_id'), 'report_admin_suggestions', ['report_id'], unique=False)
    op.create_table('report_admin_notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('report_admin_notes_admin_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_admin_notes_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('report_admin_notes_pkey'))
    )
    op.create_index(op.f('ix_report_admin_notes_report_id'), 'report_admin_notes', ['report_id'], unique=False)
    # ### end Alembic commands ###
