"""Sync assessment evidence with media model and enhance media with security features

Revision ID: 57c58cebc89e
Revises: dffc287324b6
Create Date: 2026-04-22 17:31:10.715623
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57c58cebc89e'
down_revision = 'dffc287324b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_evidence_files', sa.Column('media_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('assessment_evidence_files_uploaded_by_fkey'), 'assessment_evidence_files', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_evidence_files', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assessment_evidence_files', 'sha256')
    op.drop_column('assessment_evidence_files', 'uploaded_by')
    op.drop_column('assessment_evidence_files', 'mime_type')
    op.drop_column('assessment_evidence_files', 'scan_status')
    op.drop_column('assessment_evidence_files', 'file_size_bytes')
    op.drop_column('assessment_evidence_files', 'original_filename')
    op.drop_column('assessment_evidence_files', 'storage_key')
    op.add_column('media', sa.Column('sha256', sa.String(length=64), nullable=False))
    op.add_column('media', sa.Column('scan_status', sa.Enum('pending', 'clean', 'infected', 'failed', name='malware_scan_status'), nullable=False))
    op.add_column('media', sa.Column('uploaded_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'media', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'uploaded_by')
    op.drop_column('media', 'scan_status')
    op.drop_column('media', 'sha256')
    op.add_column('assessment_evidence_files', sa.Column('storage_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('scan_status', postgresql.ENUM('pending', 'clean', 'infected', 'failed', name='malware_scan_status'), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('assessment_evidence_files', sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessment_evidence_files', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_evidence_files_uploaded_by_fkey'), 'assessment_evidence_files', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.drop_column('assessment_evidence_files', 'media_id')
    # ### end Alembic commands ###
