"""Change checklist version from integer to string for semantic versioning

Revision ID: 907b3a2cc891
Revises: 27fb702f917a
Create Date: 2026-04-22 18:55:16.860778
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907b3a2cc891'
down_revision = '27fb702f917a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklists', 'version',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklists', 'version',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
