"""Add how_it_works field for customer hover tooltips

Revision ID: b5e87f7d0057
Revises: 2b1fbe30fdaf
Create Date: 2026-04-22 19:28:48.680763
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e87f7d0057'
down_revision = '2b1fbe30fdaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_question_translations', sa.Column('how_it_works', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_question_translations', 'how_it_works')
    # ### end Alembic commands ###
