"""Add media model and update checklist questions with image relationships

Revision ID: dffc287324b6
Revises: 20260422_0002
Create Date: 2026-04-22 17:09:06.798025
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffc287324b6'
down_revision = '20260422_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_section_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['checklist_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'section_id', name='uq_assessment_section_score')
    )
    op.create_foreign_key(None, 'access_windows', 'checklists', ['checklist_id'], ['id'], ondelete='SET NULL')
    op.alter_column('assessment_answers', 'answer_option_code_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.add_column('checklist_question_answer_options', sa.Column('illustrative_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'checklist_question_answer_options', 'media', ['illustrative_image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_checklist_question_translations_language'), 'checklist_question_translations', type_='unique')
    op.add_column('checklist_questions', sa.Column('illustrative_image_id', sa.UUID(), nullable=True))
    op.alter_column('checklist_questions', 'severity_code_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_index(op.f('ix_checklist_questions_parent_question_id'), table_name='checklist_questions')
    op.create_foreign_key(None, 'checklist_questions', 'media', ['illustrative_image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('checklist_questions', 'illustrative_image_url')
    op.drop_constraint(op.f('uq_checklist_section_translations_language'), 'checklist_section_translations', type_='unique')
    op.drop_constraint(op.f('uq_checklist_translations_language'), 'checklist_translations', type_='unique')
    op.alter_column('checklists', 'status_code_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_constraint(op.f('mfa_totp_user_id_key'), 'mfa_totp', type_='unique')
    op.drop_index(op.f('ix_mfa_totp_user_id'), table_name='mfa_totp')
    op.create_index(op.f('ix_mfa_totp_user_id'), 'mfa_totp', ['user_id'], unique=True)
    op.drop_constraint(op.f('payments_stripe_payment_intent_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_unique_constraint(op.f('payments_stripe_payment_intent_id_key'), 'payments', ['stripe_payment_intent_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_mfa_totp_user_id'), table_name='mfa_totp')
    op.create_index(op.f('ix_mfa_totp_user_id'), 'mfa_totp', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('mfa_totp_user_id_key'), 'mfa_totp', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('checklists', 'status_code_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_checklist_translations_language'), 'checklist_translations', ['checklist_id', 'language_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_checklist_section_translations_language'), 'checklist_section_translations', ['section_id', 'language_id'], postgresql_nulls_not_distinct=False)
    op.add_column('checklist_questions', sa.Column('illustrative_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checklist_questions', type_='foreignkey')
    op.create_index(op.f('ix_checklist_questions_parent_question_id'), 'checklist_questions', ['parent_question_id'], unique=False)
    op.alter_column('checklist_questions', 'severity_code_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('checklist_questions', 'illustrative_image_id')
    op.create_unique_constraint(op.f('uq_checklist_question_translations_language'), 'checklist_question_translations', ['question_id', 'language_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'checklist_question_answer_options', type_='foreignkey')
    op.drop_column('checklist_question_answer_options', 'illustrative_image_id')
    op.alter_column('assessment_answers', 'answer_option_code_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_constraint(None, 'access_windows', type_='foreignkey')
    op.drop_table('assessment_section_scores')
    op.drop_table('media')
    # ### end Alembic commands ###
