"""add_approved_to_suggestion_type_enum

Revision ID: e1fc5775ab6e
Revises: 20260501_0002_merge_support_tickets_and_question_code_heads
Create Date: 2026-05-01 17:25:58.192513
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fc5775ab6e'
down_revision = '20260501_0002_merge_support_tickets_and_question_code_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    
    # Add 'approved' to suggestion_type enum
    op.execute("ALTER TYPE suggestion_type ADD VALUE 'approved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
